#!/bin/bash
apt-get update && apt-get install curl wget unzip -y
curl -L https://bootstrap.saltstack.com -o bootstrap_salt.sh
bash bootstrap_salt.sh
wget https://github.com/martyni/salt/archive/master.zip
unzip master.zip -d /srv
echo "file_client: local" >/etc/salt/minion
echo "file_roots:"        >>/etc/salt/minion
echo "  base:"            >>/etc/salt/minion
echo "   - /srv/salt-master/salt" >>/etc/salt/minion
service salt-minion restart
salt-call state.highstate
